name: Build docs

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build-docs:
    
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[docs]
    - name: Update Sphinx docs
      run: |
        cd docs
        make html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/_build/html 
